import { createAction, props } from '@ngrx/store';
import { MessageDto } from '../feature/model/messsage.model';

export const getMesseges = createAction('[Messages] Get Messages');

export const getMessegesSuccess = createAction(
  '[Messages] Get Messages success',
  props<{ messages: MessageDto[] }>()
);
export const getMessegesFailure = createAction(
  '[Messages] Get Messages failure',
  props<{ error: string }>()
);

export const addMessage = createAction(
  '[Messages] Add Messages',
  props<{ message: MessageDto }>()
);

export const addMessageSuccess = createAction(
  '[Messages] Add Messages success',
  props<{ autogeneratedID: string; message: MessageDto }>()
);

export const addMessageFailure = createAction(
  '[Messages] Add Messages failure',
  props<{ error: string }>()
);

export const removeMessage = createAction(
  '[Messages] Remove Messages',
  props<{ autogeneratedID: string }>()
);

export const removeMessageSuccess = createAction(
  '[Messages] Remove Messages success',
  props<{ autogeneratedID: string }>()
);

export const removeMessageFailure = createAction(
  '[Messages] Remove Messages failure',
  props<{ error: string }>()
);
