import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { MessageDto } from './feature/model/messsage.model';
import { messagesSelector } from './store/app.selectors';

const envUrl =
  'https://messeges-project1233122-default-rtdb.europe-west1.firebasedatabase.app/';

@Injectable({
  providedIn: 'root',
})
export class appService {
  constructor(private http: HttpClient) {}

  fetchMesseges(): Observable<MessageDto[]> {
    return this.http.get<MessageDto[]>(`${envUrl + '.json'}`);
  }

  addMessage(message: MessageDto): Observable<any> {
    return this.http.post<any>(`${envUrl + '.json'}`, {
      name: message.name,
      message: message.message,
    });
  }

  removeMessage(autogeneratedID: string): Observable<any> {
    return this.http.delete<any>(`${envUrl + autogeneratedID + '.json'}`);
  }
}
